// USER DEFINED PINS  - - - - - - - PROVVISORIO
// BATTERY LEVEL 
#define PIN_BATTERY_LED 12 
#define PIN_SECOND_LED 13 
#define PIN_BATTERY_LEVEL 0

// PROXIMITY_SENSOR
#define PIN_PROXIMITY_SENSOR_ECHO 2
#define PIN_PROXIMITY_SENSOR_TRIG 3

// ALTITUDE_SENSOR
#define PIN_ALTITUDE_SENSOR_SDA 4
#define PIN_ALTITUDE_SENSOR_SCL 5