// ATmega32 pinmap
// @author: Sebastiano Cocchi

// ESC
#define PIN_ESC_1 4
#define PIN_ESC_2 5
#define PIN_ESC_3 6
#define PIN_ESC_4 7

// RECEIVER
#define PIN_RECEIVER_1 8
#define PIN_RECEIVER_2 9
#define PIN_RECEIVER_3 10
#define PIN_RECEIVER_4 11

// LED
#define PIN_BATTERY_LED 12 
#define PIN_SECOND_LED 13 

// BATTERY LEVEL
#define PIN_BATTERY_LEVEL 0

// PROXIMITY_SENSOR
#define PIN_PROXIMITY_SENSOR_ECHO 2
#define PIN_PROXIMITY_SENSOR_TRIG 3

// ALTITUDE_SENSOR
#define PIN_ALTITUDE_SENSOR_SDA 4
#define PIN_ALTITUDE_SENSOR_SCL 5
